version: '3.8'
services:
  app:
    image: uo-green-revenue
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - .:/app/frontend
        - /app/frontend/node_modules
        - /app/frontend/.next
    ports:
      - "4002:8080"